name: app_comanda
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  dartz: ^0.10.1
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/roboto/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/roboto/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/roboto/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/roboto/RobotoCondensed-Light.ttf
        - asset: assets/fonts/roboto/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/roboto/RobotoCondensed-Regular.ttf
